.yml compilation

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -14,6 +14,21 @@ jobs:
       - name: Checkout du code
         uses: actions/checkout@v4
 
+      - name: Set up Python
+        uses: actions/setup-python@v2
+        with:
+          python-version: '3.9'
+
+      - name: Install dependencies
+        run: |
+          python -m pip install --upgrade pip
+          pip install -r requirements.txt
+
+      - name: Verify server starts
+        run: |
+          nohup python manage.py runserver & sleep 5;
+          curl -f http://127.0.0.1:8000 || (echo "Server failed to start" && exit 1)
+
       - name: Log in to Docker Hub
         uses: docker/login-action@v3
         with:
